### ISSUE TITLE
GamePanel -> GameDetail 

### ISSUE THREAD

**Issue by andtur** [wwayne/react-native-nba-app#12]
Hi,

It is more perhaps stupid question than an issue. I am bit lost in understanding your code. You open the GameDetails with the navigator from GamePanel. In the route you place game and date. In the GameDetails you get actions from the props. Where do they come from?

Thank you

**Comment by wwayne** [comment]
@andtur 
This is a good question. To put it simply, I made use of `Navigator`.

You can see in `app > containers > Game.js` line 22, every component in Game page is supported(rendered) by `Navigator`, and the same props is passed in by Navigator.

You may wonder where `{...this.props}` come from, you can check the `App.js` in containers folder, line 41, it comes from Redux store.
