### ISSUE TITLE
can't nav to GameDetail page

### ISSUE THREAD

**Issue by mydearxym** [wwayne/react-native-nba-app#15]
love your work!

i download the latest repo  and run it on my iOS simulator , everything works fine except  navigate to the GameDetail page 

![image](https://cloud.githubusercontent.com/assets/6184465/12867350/2fdd49d8-cd26-11e5-8162-aea171e4d788.png)

**Comment by wwayne** [comment]
@mydearxym these are unstart game, only finish game or live game have detail. You can click the button on the right top to check the games in yesterday which are finished games and have game details.
