### ISSUE TITLE
team crash

### ISSUE THREAD

**Issue by recwert** [wwayne/react-native-nba-app#16]
the process will crash when click the team tab

**Comment by wwayne** [comment]
On iOS or Android? it's working well on my iPhone, I haven't tested it on any Android device

**Comment by recwert** [comment]
on ios  redbox output error "JSON parse error:unrecognized token `<` "

**Comment by wwayne** [comment]
Ok, I will check this later, maybe that's because today's data.... it's all good in the last 2 months

**Comment by wwayne** [comment]
Looks the NBA official website has abandoned my access to this API, anyway, I will try to parser the website to get the data
