### ISSUE TITLE
Not able to run with Android

### ISSUE THREAD

**Issue by sumanbogati** [wwayne/react-native-nba-app#18]
When I try to test this app with my android setup, I am not able run this app locally. Here is the `react-native run-android` command throws the error

`Command`run-android`unrecognized. Did you mean to run this inside a react-nati
ve project?`

However I ran the command from inside of project.

**Comment by wwayne** [comment]
Maybe that's because of the update of cli? you can check something here https://github.com/facebook/react-native/issues/2880
But the app can't visit for the moment because NBA official website has changed the API
