### ISSUE TITLE
Error: app broken now?

### ISSUE THREAD

**Issue by simonjblack** [wwayne/react-native-nba-app#19]
I love the look of the app and the article but unfortunately I can't get it to work :( 

I follow the instructions to install, but when I get it running I only get empty 'game' and 'players' screens, while clicking 'teams' results in a red screen error: `Unexpected token < in JSON at position 0`. I've replicated this twice with fresh git clones. I'm on XCode 7.3.1, OSx El Capitan and haven't made any changes to dependencies. I also get the two below errors in console:
`The regenerator/runtime module is deprecated; please import regenerator-runtime/runtime instead.`
`'//@ sourceURL' and '//@ sourceMappingURL' are deprecated, please use '//# sourceURL=' and '//# sourceMappingURL=' instead.`

Do you know of any way to fix this? I'd love to give the app a try!

**Comment by wwayne** [comment]
The NBA official blocked the team related API, that why the APP breaks.
No plan for fixing this, maybe next season :)
