### ISSUE TITLE
Improve NavigationBar

### ISSUE THREAD

**Issue by sibelius** [wwayne/react-native-nba-app#3]

**Comment by wwayne** [comment]
Just move a lot of things out of navigation bar, I found I used it in a wrong way.
if you pass `props` or `state` which lead to re-mount into navigation can cause `blink` when switch between navigations.

**Comment by sibelius** [comment]
I'm still trying to figure out how to use Navigator and Navigator.NavigationBar, the NavigationBar is on top of the View that I render on renderScene, do you have any ideia of how to solve that?

**Comment by wwayne** [comment]
I think you can regard `Navigator` as a function and `Navigator.NavigationBar` just as a view, you can use Navigator's function to switch between different pages even just render an empty NavigationBar  `<View></View>` in your `renderScene`.

I had some experience on IOS development, I think the first you should tell difference between `Tab` and `Navigator`, it would help you to figure out where to use `Navigator`.

And this [example](http://stackoverflow.com/questions/29335523/react-native-custom-navigation-with-navigator-component)(in the question part) is much better than official doc.

**Comment by sibelius** [comment]
@wwayne thanks for your help
