### ISSUE TITLE
意见征求

### ISSUE THREAD

**Issue by songxiaoliang** [wwayne/react-native-nba-app#32]
你好，想仿照当前App使用Flutter实现，征求下您的建议，期待你的回复~

**Comment by wwayne** [comment]
@songxiaoliang 你好，因为这个app是几年前一时兴趣做的也没有维护，所以不好意思并不能建议什么
如果你想参照设计可以在README里面找到设计文件sketch的连接

**Comment by songxiaoliang** [comment]
@wwayne 好的，非常感谢！
