### ISSUE TITLE
Improve and fix plan

### ISSUE THREAD

**Issue by wwayne** [wwayne/react-native-nba-app#8]
### Game list
- [x] Should stop request when entering the game detail page and resume when turn back
- [x] The animation between navigator need to be smooth (check InteractionManager)
- [x] componentWillReceiveProps has been triggered twice, which could affect setTimeout of getting data
- [ ] Android: space is insufficient for the list
- [ ] Android: Need a cross-platform activity indicator 
### Game Detail
- [x] Page seems can't trigger refresh action automatically
- [ ] The first line and first column of the list should be fixed when scrolling (check PanResponder)
- [ ] Try to add video for this page
- [x] setTimeout trigger twice
- [ ] Android: Players plusMinus chart can't show tooltip
### Player search
- [ ] Activity indicator when searching
### Teams
- [ ] Activity indicator in navigation
- [ ] Android: List space is not enough
- [ ] Android: Page switch will stuck in the process(maybe caused by simulator)

**Comment by ericmachine88** [comment]
any plans to update to the latest react native?

**Comment by wwayne** [comment]
No, I don't have plan to update this project for the moment

**Comment by holtenko** [comment]
A sad story...

**Comment by johng** [comment]
What version of react native does it support?

**Comment by wwayne** [comment]
From the package.json, it supports`^0.17.0`

**Comment by ericmachine88** [comment]
is it a big learning curve to switch to latest? it seems rn breaks easily across newer versions. Any advices to share?

**Comment by wwayne** [comment]
I don't know because I spent all my time on other things since then, but I personally would like to switch to the latest version next time I using RN. Actually I have to deal with a lot of wired problems when I made this app so that it won't break easily and have a slightly better performance..

**Comment by ericmachine88** [comment]
noted :)
